Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-es'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-es'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-es'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-es'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-es'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-es'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-es'.
Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-es'.
Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-es'.
Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 361, in receive
    sender_id = self._extract_sender(request)
  File "C:\Users\ayesa1\rasaExample\rasaPrueba\lib\site-packages\rasa_core\channels\channel.py", line 329, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'NoneType' object has no attribute 'get'
